src/AppBundle/Entity/BaseEntity.php
<?php
// src/AppBundle/Entity/BaseEntity.php
namespace AppBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

class BaseEntity {

    /**
     * @ORM\Column(name="created_at", type="datetime")
     */
    protected $created_at;

    /**
     * @ORM\Column(name="updated_at", type="datetime")
     */
    protected $updated_at;

    public function getCreatedFormat() {
        return $this->getCreatedAt()->format('d.m.Y H:i:s');
    }

    public function getUpdatedFormat() {
        return $this->getCreatedAt()->format('d.m.Y H:i:s');
    }

    public function getUpdatedAtDatetime() {
        return $this->getCreatedAt()->format('Y-m-d H:i:s');
    }

    public function getCreatedAtDatetime() {
        return $this->getCreatedAt()->format('Y-m-d H:i:s');
    }

    /**
     * Set created_at
     *
     * @param \DateTime $createdAt
     * @return Interest
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;

        return $this;
    }

    /**
     * Get created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }


    /**
     * Set updated_at
     *
     * @param \DateTime $updatedAt
     * @return Interest
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;

        return $this;
    }

    /**
     * Get updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Add span to first letter of $string
     * @param unknown_type $string
     */
    protected function firstLetterWithSpan($string) {
        $first = substr($string, 0, 1);

        return '<span>' . $first . '</span>' . substr($string, 1);
    }

    /**
     * Return url by $str
     *
     * @param string $str
     * @return string
     */
    public function cleanUrl($str) {
        $clean = preg_replace("/[^a-zA-Z0-9\/_|+ -]/", '', $str);
        $clean = strtolower(trim($clean, '-'));
        $clean = preg_replace("/[\/_|+ -]+/", '-', $clean);

        $clean = substr($clean, 0, 100);

        return $clean;
    }
    // public function findEntitiesByString($str){
    //     return $this->getEntityManager()
    //         ->createQuery(
    //             'SELECT e
    //             FROM AppBundle:News n
    //             WHERE n.name LIKE :str'
    //         )
    //         ->setParameter('str', '%'.$str.'%')
    //         ->getResult();
    // }
}

src/AppBundle/Form/ContactForm.php
<?php
// src/AppBundle/Form/ContactForm.php

namespace AppBundle\Form;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class ContactForm extends AbstractType 
{
    const FORM_NAME = 'contact';
    
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder->add('name', 'text', array(
                'label' => 'Name',
                'attr' => array ('placeholder' => 'Name'),
                'required' => true
        ));
        
        $builder->add('email', 'email', array(
                'label' => 'E-mail', 
                'attr' => array ('placeholder' => 'E-mail'),
                'required' => true
        ));
        
        $builder->add('phone', 'text', array(
                'label' => 'Phone number', 
                'attr' => array ('placeholder' => 'Phone number'),
                'required' => true
        ));
        
        $builder->add('message', 'textarea', array(
                'label' => 'Tell us',
                'attr' => array ('placeholder' => 'Tell us about your case'),
                'required' => true
        ));
    }
    
    public function getName() {
        return self::FORM_NAME;
    }
    
    public function setDefaultOptions(OptionsResolverInterface $resolver) {
        $resolver->setDefaults(array(
            'data_class'      => 'AppBundle\Entity\Interest',
            'csrf_protection' => false,
        ));
    }
}

src/AppBundle/Controller/ContactController.php
<?php

namespace AppBundle\Controller;

use Plugins\ContentBundle\Entity\Content;

use AppBundle\Lib\Tools;

use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

use AppBundle\Entity\Interest;

use AppBundle\Form\ContactForm;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class ContactController extends BaseController
{

    /**
     * Contact action
     */
    public function contactAction() {
        $contactMetaBlock = $this->getContentRepository()->findOneByKey(Content::CONTENT_META_CONTACT_PAGE);
        $whyUsBlockContacts = $this->getContentRepository()->findOneByKey(Content::CONTENT_WHY_US_CONTACTS);

        return $this->render('AppBundle:Contact:contact.html.twig', array(
                'whyUsBlockContacts'   => $whyUsBlockContacts,
                'page'         => $contactMetaBlock,
            ));
    }

    /**
     * Render form action
     */
    public function formAction() {
        $form = $this->createForm(new ContactForm(), new Interest());

        return $this->render('AppBundle:Contact:form.html.twig', array(
                'form' => $form->createView(),
                'formName' => ContactForm::FORM_NAME,
        ));
    }

    /**
     * Send action
     */
    public function sendAction(Request $request) {
        try {
            $interest = new Interest();
            $form = $this->createForm(new ContactForm(), $interest);

            if ($request->getMethod() == 'POST') {
                $form->bind($this->getRequest()->get(ContactForm::FORM_NAME));
                if ($form->isValid()) {
                    $interest->setIpAddress($request->getClientIp());
                    $this->getInterestRepository()->save($interest);

                    if ($this->isProd() || true) {
                        /* Send email to manager */
                        $body = $this->renderView('AppBundle:Contact:email_to_manager.html.twig', array(
                            'interest' => $interest,
                        ));
                        $subject = '[Sharovalaw.Com] New message from the site';
                        Tools::sendEmail($this, $subject, $body, $this->container->getParameter('mailer_user'), $this->container->getParameter('contact_email'));
                    }

                } else {
                    /* @var $error \Symfony\Component\Form\FormError */
                    $error_list = $this->getFormatedErrorMessages($form);
                    $errors = array();
                    foreach ($error_list as $row => $error) {
                        $errors[] = $row;
                    }
                    throw new \Exception(implode(',', $errors));
                }
            }

            $message = 'Your message has been successfully sent';
            $success = true;
        } catch (\Exception $e) {
            $this->get('logger')->debug($e->getMessage());
            $message = $this->isDev() ? $e->getMessage() : 'Problem with sending message ';
            $success = false;
        }

        return $this->getAjaxResponse($success, array('message' => $message));
    }
}

src/AppBundle/Resources/views/Contact/contact.html.twig
{% extends 'AppBundle::layout.html.twig' %}

{% block title %}{{- page.metatitle ? page.metatitle : parent() -}}s - New York Law Frim{% endblock %}
{% block meta_keywords %}{{- page.metakeywords ? page.metakeywords : parent() -}}s - New York Law Frim{% endblock %}
{% block meta_description %}{{- page.metadescription ? page.metadescription : parent() -}}s - New York Law Frim{% endblock %}
{% block og_title %}{{- page.metatitle ? page.metatitle : parent() -}}{% endblock %}
{% block og_descr %}{{- page.metadescription ? page.metadescription : parent() -}}{% endblock %}
{% block last_updated_block %}{{ page.updatedAtDatetime }}{% endblock %}

{% block bodyId %}contacts{% endblock %}
{% block bodyClass %}contacts{% endblock %}

{% block content %}

		<wrapper>
    <section id="map">

			<div class="map-self">
				<div class="row">
					<script type="text/javascript">
					console.log('zhopa');
					console.log($(".overlay"));
					$(".overlay").on("click", function() {
						console.log('idi nahuj');
						window.location = $(this).find("a").attr("href");
						// return false;
					});
					</script>
					<!-- <div class="overlay">
						<a href="https://www.google.pl/maps/place/Law+Office+of+Yelena+Sharova,+P.C./@40.7633087,-73.9732639,15z/data=!4m5!3m4!1s0x0:0x8bf0a6bb2ad8f1a5!8m2!3d40.7633087!4d-73.9732639"></a>
					</div> -->
					<div class="map-iframe m320">{{ map_1024 | raw}}</div>
					<div class="map-iframe m576">{{ map_1024 | raw}}</div>
					<div class="map-iframe m768">{{ map_768 | raw}}</div>
					<div class="map-iframe m1024">{{ map_1024 | raw}}</div>
					<div class="map-iframe m1440">{{ map_1440 | raw}}</div>
					<div class="map-iframe m1920">{{ map_1440 | raw}}</div>
					<div class="map-iframe m2560">{{ map_1440 | raw}}</div>
					<div class="info">
						<ul class="address">
							<li class="part addr">
								<h4>Addres 1</h4>
								<p>
									{{ contact_address_short1 }}
									<br>
									{{ contact_address_state }} {{ contact_zip1 }}
								</p>
							</li>
							<li class="part addr">
								<h4>Addres 2</h4>
								<p>
									{{ contact_address_short2 }}
									<br>
									{{ contact_district2 }}, {{ contact_address_state }} {{ contact_zip2 }}
								</p>
							</li>
							<div class="part phone">
								<h4>Contact</h4>
								<p>
									Phone: {{ contact_phone }}
									<br>
									Fax: {{ contact_fax }}
									<br>
									<a href="mailto:{{ contact_email1 }}?subject=From Contacts Page">{{ contact_email1 }}</a>
								</p>
							</div>
						</ul>
						<div class="form">
							{% include "AppBundle:Contact:contact_block_form.html.twig" %}
						</div>
					</div>
				</div>
			</div>
		</section>

    <section id="about">
			<div class="container">
			  <div class="row row-eq-height">
			    <div class="liberty">
						<img id="sl" src="/img/sl.png" alt="Sharova Law Firm">
			    </div>
					<div class="why-us">
						<h3>{{ whyUsBlockContacts.name  | replace({" Contacts":""})}}</h3>
            {{ whyUsBlockContacts.content | raw }}
            <div class="text-containter">
              <p>Knowledge without passion can be considered a recital of facts at best.</p>
              <p>You don’t want a lawyer going to court with you, fighting for you, while just reciting the
                  facts. You need a passionate fighter who is willing to put the work in, who can empathize
                  with you. You also need a team of attorneys that do know the facts and are willing to
                  uncover them to preserve their client’s rights and lives. The attorneys at the Law Office of
                  Yelena Sharova P.C. are the attorneys you are looking for, whether it is a criminal, civil
                  or family matter; these defense attorneys are the cream of the crop. Call for a Free
                  15-minute Consultation and see why hiring the Law Office of Yelena Sharova is right for you.
                  Don’t put your life on hold.</p>
							<h3>CALL TODAY!</h3>
							<hr>
            </div>
						{% include "default/fb.html.twig" %}
						</div>
					</div>
			  </div>
			</div>
		</section>
  </wrapper>
{% endblock %}

src/AppBundle/Resources/views/Contact/contact_block_form.html.twig
{% block contactSection %}
		<div id="contactus">
			<h2>Contact us now</h2>
			<p>Leave your message in the form below</p>
			{% render controller("AppBundle:Contact:form") %}
		</div>
{% endblock %}

src/AppBundle/Resources/views/Contact/email_to_manager.html.twig
{% block body %}
<div>
<h3>New message!</h3>

<b>Date:</b><br/>
<i>{{ interest.createdFormat }}</i><br><br>

<b>Name:</b><br/>
<i>{{ interest.name }}</i><br><br>

<b>Email:</b><br/>
<i><a href="mailto:{{ interest.email }}">{{ interest.email }}</a></i><br><br>

<b>Phone:</b><br/>
<i>{{ interest.phone }}</i><br><br>

<b>Message:</b><br/>
<i>{{ interest.message}}</i><br><br>

Best regards,
Sharovalaw.com
</div>
{% endblock %}

src/AppBundle/Resources/views/Contact/form.html.twig
{% block contactForm %}
		<form action="{{ path('app_contact_send') }}" method="post" id="contact-form" novalidate>
			<div class="form-data">
				<lable class="action">name</lable>
				{{ form_widget(form.name, {'attr': {'placeholder': ' '}}) }}
			</div>
			<div class="form-data">
				<lable class="action">email</lable>
				{{ form_widget(form.email, {'attr': {'placeholder': ' ', 'type': 'email'}}) }}
			</div>
			<div class="form-data">
				<lable class="action">phone</lable>
				{{ form_widget(form.phone, {'attr': {'placeholder': ' ', 'type': 'tel'}}) }}
			</div>
			<div class="form-data">
				<lable>message</lable>
				{{ form_widget(form.message, {'attr': {'placeholder': 'Tell Us About Your Case'}}) }}
			</div>

			<button type="submit" class="pbtn btn btn-primary">contact us</button>
		</form>
<script>
$(document).ready(function() {
    Form.init({
        target: "#{{ formName }}-form",
        validation: {
            rules: {
                "{{ formName }}[name]": {
                    required: true,
                    minlength: 3,
                    maxlength: 200
                },
                "{{ formName }}[email]": {
                    required: true,
                    minlength: 3,
                    maxlength: 255
                },
                "{{ formName }}[phone]": {
                    required: true,
                    phone: true
                },
                "{{ formName }}[message]": {
                    required: true,
                }
            },
            messages: {
                "{{ formName }}[name]": {
                    required: "Name is required.",
                    minlength: "Name must be at least 3 characters.",
                    maxlength: "Name must be no more than 200 characters.",
                },
                "{{ formName }}[email]": {
                    required: "Email is required.",
                    maxlength: "Email must be no more than 255 characters.",
                },
                "{{ formName }}[phone]": {
                    required: "Phone is required.",
                }
            }
        }
    });
});
</script>
{% endblock %}