src/AppBundle/Entity/BaseEntity.php
<?php
// src/AppBundle/Entity/BaseEntity.php
namespace AppBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

class BaseEntity {

    /**
     * @ORM\Column(name="created_at", type="datetime")
     */
    protected $created_at;

    /**
     * @ORM\Column(name="updated_at", type="datetime")
     */
    protected $updated_at;

    public function getCreatedFormat() {
        return $this->getCreatedAt()->format('d.m.Y H:i:s');
    }

    public function getUpdatedFormat() {
        return $this->getCreatedAt()->format('d.m.Y H:i:s');
    }

    public function getUpdatedAtDatetime() {
        return $this->getCreatedAt()->format('Y-m-d H:i:s');
    }

    public function getCreatedAtDatetime() {
        return $this->getCreatedAt()->format('Y-m-d H:i:s');
    }

    /**
     * Set created_at
     *
     * @param \DateTime $createdAt
     * @return Interest
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;

        return $this;
    }

    /**
     * Get created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }


    /**
     * Set updated_at
     *
     * @param \DateTime $updatedAt
     * @return Interest
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;

        return $this;
    }

    /**
     * Get updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Add span to first letter of $string
     * @param unknown_type $string
     */
    protected function firstLetterWithSpan($string) {
        $first = substr($string, 0, 1);

        return '<span>' . $first . '</span>' . substr($string, 1);
    }

    /**
     * Return url by $str
     *
     * @param string $str
     * @return string
     */
    public function cleanUrl($str) {
        $clean = preg_replace("/[^a-zA-Z0-9\/_|+ -]/", '', $str);
        $clean = strtolower(trim($clean, '-'));
        $clean = preg_replace("/[\/_|+ -]+/", '-', $clean);

        $clean = substr($clean, 0, 100);

        return $clean;
    }
    // public function findEntitiesByString($str){
    //     return $this->getEntityManager()
    //         ->createQuery(
    //             'SELECT e
    //             FROM AppBundle:News n
    //             WHERE n.name LIKE :str'
    //         )
    //         ->setParameter('str', '%'.$str.'%')
    //         ->getResult();
    // }
}

src/AppBundle/Entity/BasePhotoEntity.php
<?php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;


class BasePhotoEntity extends BaseEntity
{
    const UPLOAD_DIR_NAME = 'uploads';

    protected $subfolder = '';


    /**
     * Unmapped property to handle file uploads
     */
    protected $photo;

    /**
     * @ORM\Column(name="filename", type="string", length=255,  nullable=true)
     */
    protected $filename;

    public function getPhotoFullPath()
    {
        $pathToFile = self::UPLOAD_DIR_NAME . "/";
        if (!empty($this->subfolder)) {
            $pathToFile .= $this->subfolder . "/";
        }

        if (empty($this->getFilename())) {
            return null;
        }

        return $pathToFile . $this->getFilename();
    }

    /**
     * Lifecycle callback to upload the file to the server
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function lifecycleFileUpload()
    {
        if (null !== $this->getPhoto()) {

            $filename = $this->getPhoto()->getClientOriginalName();
            $this->setFilename($filename);

            $this->getPhoto()->move(
                $this->getUploadRootDir(),
                $filename
            );

            $this->setFilename($filename);
            $this->setPhoto(null);
        }
    }

    /**
     * Get upload root dir
     */
    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        $uploadDir = __DIR__ . '/../../../web/' . self::UPLOAD_DIR_NAME;
        if (!empty($this->subfolder)) {
            $uploadDir .= DIRECTORY_SEPARATOR . $this->subfolder;
        }
        return $uploadDir;
    }

    /**
     * Set photo
     *
     * @param UploadedFile $photo
     */
    public function setPhoto(UploadedFile $photo = null)
    {
        $this->photo = $photo;
    }

    /**
     * Get photo
     *
     * @return UploadedFile
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * Set filename
     *
     * @param string $filename
     * @return Attorney
     */
    public function setFilename($filename)
    {
        $this->filename = $filename;

        return $this;
    }

    /**
     * Get filename
     *
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }
}

src/AppBundle/Entity/Quote.php
<?php
// src/AppBundle/Entity/Quote.php
namespace AppBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\QuoteRepository")
 
 * @ORM\Table(name="Quote")
 */
class Quote extends BaseEntity {

    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    
    /**
     * @ORM\Column(name="name", type="string", length=255)
     */
    protected $name;
    
    /**
     * @ORM\Column(name="quote", type="string", length=500)
     */
    protected $quote;
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Quote
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }
    
    /**
     * Get name with span for $first letter
     *
     * @return string
     */
    public function getNameS()
    {
        return $this->firstLetterWithSpan($this->name);
    }

    /**
     * Set quote
     *
     * @param string $quote
     * @return Quote
     */
    public function setQuote($quote)
    {
        $this->quote = $quote;

        return $this;
    }

    /**
     * Get quote
     *
     * @return string 
     */
    public function getQuote()
    {
        return $this->quote;
    }
    
    /**
     * Get name with span for $first letter
     *
     * @return string 
     */
    public function getQuoteS()
    {
        return $this->firstLetterWithSpan($this->quote);
    }
}

src/AppBundle/Resources/views/App/about_us.html.twig
{% extends 'AppBundle::layout.html.twig' %}

{% block title %}{{- page.metatitle ? page.metatitle : parent() -}}{% endblock %}
{% block meta_keywords %}{{- page.metakeywords ? page.metakeywords : parent() -}}{% endblock %}
{% block meta_description %}{{- page.metadescription ? page.metadescription : parent() -}}{% endblock %}
{% block og_title %}{{- page.metatitle ? page.metatitle : parent() -}}{% endblock %}
{% block og_descr %}{{- page.metadescription ? page.metadescription : parent() -}}{% endblock %}
{% block last_updated_block %}{{ page.updatedAtDatetime }}{% endblock %}

{% block bodyId %}about{% endblock %}
{% block bodyClass %}home{% endblock %}

{% block content %}

<div id="static-menu" class="home">
	<ul>
		<li class='cur'><a href="#sub-about">About Us</a></li>
		<li><a href="#sub-pa-block">Practice Areas</a></li>
		<li><a href="#sub-region-text">Regions</a></li>
		<li><a href="#sub-team-list">Our Team</a></li>
		<li><a href="#contact-baner">Contact Us</a></li>
	</ul>
</div>

<wrapper>
	<section id='home-about' class="container">
		<div class="row">
			<div class="sub-block" id='sub-about'>
				<h2>About us</h2>
				<p>At Sharova Law Firm, we believe that communication is the first and most effective line of defense. When it comes to legal matters, we know how important it is for you to be heard and represented. We go above and beyond for our clients, priding ourselves on our availability and responsiveness.</p>
				<p>By being sensitive to your situation and tough in the courtroom, we will work with you to resolve your case in a professional and timely manner. We have been there for our clients through thick and thin, and will be there for you when you need us most. Even in complicated scenarios, we are able to navigate the complex legal systems in New York, New Jersey and the federal government.</p>
			</div>

			<div class="sub-block" id='sub-pa-text'>
				<div class="middle">
					<h2>Experienced Lawyers on Your Side</h2>
					<p>We know that you have many choices when it comes to deciding which New York or New Jersey law firm to hire. What makes us different is that we have extensive experience in a wide array of areas and we are equally qualified in each of them. We know what’s necessary in order to navigate the legal system on your behalf, particularly in the following areas of practice:</p>
				</div>
			</div>
			<div class="sub-block" id='sub-pa-block'>
				{% render controller("PluginsPracticAreaBundle:PracticArea:practicAreasShortAbout") %}
			</div>

			<div class="sub-block" id="sub-region-img">

			</div>
			<div class="sub-block" id="sub-region-text">
				<h2>Proudly Serving New York and New Jersey</h2>
				<p>While our offices are located in the heart of New York City, our ability to provide legal representation and consultation extends to the following regions:</p>
				<ul>
					<li>● Eastern New York</li>
					<li>● Southern New York</li>
					<li>● Northern New York District Courts</li>
					<li>● The State of New Jersey</li>
					<li>● District Court of New Jersey</li>
				</ul>
				<p>We belong to the following associations:</p>
				<ul>
					<li>● New York County Bar Association (Manhattan)</li>
					<li>● Queens County Bar Association</li>
					<li>● Kings County Bar Association</li>
					<li>● Richmond County Bar Association</li>
					<li>● Nassau County Bar Association</li>
					<li>● Union County New Jersey Bar Association</li>
					<li>● Middlesex County New Jersey Bar Association</li>
				</ul>
			</div>

			<div class="sub-block" id="hor-text">
				<p>Whether your case involves a settlement, collaborative divorce, or the necessity of upfront resources, Sharova Law Firm will guide you through the process. As your trusted legal team, we will work toward the best possible outcome for your individual case, and provide you with the resources you need to move forward in your life.</p>
			</div>


			<div class="sub-block" id="sub-team-text">
				<h2>Working In Your Best Interests <br>Every Step Of The Way</h2>

				<p>The first step when you come to Sharova Law Firm is for us to listen closely to what your particular legal matter entails and look at it from every angle possible. Your priorities are our priorities throughout the entire process. Especially in family law and divorce cases, the welfare of your children and your safety are of the utmost importance to us as your legal team.</p>

				<p>Negotiation first, mediation next, and litigation last is the way we conduct ourselves here at Sharova Law Firm. We make sure that your matters are resolved with as little time, money, and stress as possible, while working tirelessly toward your desired outcome. Of course, we are always ready to take the actions necessary to proceed in your best interest, providing you with every potential option that might be available to you. We also know that cost may be a concern, but rest assured that we put your needs before our bottom line to make your representation as cost-effective as possible.</p>

				<p>Contact a law firm that truly cares about your wellbeing. We will do whatever it takes to find a resolution to your matter, no matter how complex your case may be.</p>

			</div>

			<div class="sub-block" id="sub-team-list">
				<h2>Our Team</h2>

				<ul>
					<li>
	          <a href="#"><img src="/img/persona/per-w.png"></a>
	          <div class="block">
	            <h3>Nettie Norton</h3>
	            <div class="info-block">
	              <h4>Type something</h4>
	              <p>
	                People like a “special” price or exclusive offer directed
	              </p>
	            </div>
	            <div class="stat-block">
	              <h4><a href="">Click to discover</a></h4>
	              <div class="statistic">
	                <ul>
	                  <li>
	                    <span>233</span>
	                    <h5>Completed Casess</h5>
	                  </li>
	                  <li>
	                    <span>33</span>
	                    <h5>Years of practice</h5>
	                  </li>
	                  <li>
	                    <span>97%</span>
	                    <h5>wining rate</h5>
	                  </li>
	                </ul>
	              </div>
	            </div>
	          </div>
	        </li>
	        <li>
	          <a href="#"><img src="/img/persona/per-m.png"></a>
	          <div class="block">
	            <h3>Henry Harper</h3>
	            <div class="info-block">
	              <h4>Type something</h4>
	              <p>
	                People like a “special” price or exclusive offer directed
	              </p>
	            </div>
	            <div class="stat-block">
	              <h4><a href="">Click to discover</a></h4>
	              <div class="statistic">
	                <ul>
	                  <li>
	                    <span>233</span>
	                    <h5>Completed Casess</h5>
	                  </li>
	                  <li>
	                    <span>33</span>
	                    <h5>Years of practice</h5>
	                  </li>
	                  <li>
	                    <span>97%</span>
	                    <h5>wining rate</h5>
	                  </li>
	                </ul>
	              </div>
	            </div>
	          </div>
	        </li>
				</ul>
			</div>
		</div>
	</section>
	<section id="contact-baner" class="home">
		<div class="back">
			<div class="cover"></div>
		</div>
			<div class="container">
				<div class="side a">
					<a href="app_dev.php"><img src="/img/lgog.svg"></a>
					<br>
					<span>
						Contact a law firm that truly cares about your wellbeing. We will do whatever it takes to find a resolution to your matter, no matter how complex your case may be.
					</span>
				</div>
				<div class="side b">
					{% include "AppBundle:Contact:contact_block_form.html.twig" %}
					<!-- <div id="contactus">
						<h2>Contact us now</h2>
						<p>Leave your message in the form below</p>
						<form action="">
							<div class="form-data">
								<lable class='action'>name</lable>
								<input type="text" name='name'>
							</div>
							<div class="form-data input">
								<lable class='action'>email</lable>
								<input type="text" name='name'>
							</div>
							<div class="form-data input">
								<lable class='action'>phone</lable>
								<input type="text" name='name'>
							</div>
							<div class="form-data">
								<lable>message</lable>
								<textarea name="msg" placeholder='Tell us about your case'></textarea>
							</div>

							<a href=""><div class="pbtn">contact us</div></a>
						</form>
					</div> -->
				</div>
			</div>
	</section>
</wrapper>
{% endblock %}

src/AppBundle/Resources/views/App/attorney_menu.html.twig
{% block verticalMenu %}
<span class="title">
    about us
</span>
<ul>
    {% for attorney in attorneys %}
    <li class="main without-background">
        <a href="{{ path("app_about_attorney", { "url" : attorney.url }) }}" title="{{ attorney.name }}" class="{{ attorney.id == activeId ? "selected" }}">{{ attorney.name }}</a>
    </li>
    {% endfor %}
</ul>
<div class="left-menu-border"></div>
{% include "AppBundle:App:bar_assoc_short.html.twig" %}

{% endblock %}

src/AppBundle/Resources/views/App/attorney_view.html.twig
{% extends 'AppBundle::layout.html.twig' %}

{% block title %}{{- page.metatitle ? page.metatitle : parent() -}}{% endblock %}
{% block meta_keywords %}{{- page.metakeywords ? page.metakeywords : parent() -}}{% endblock %}
{% block meta_description %}{{- page.metadescription ? page.metadescription : parent() -}}{% endblock %}
{% block og_title %}{{- page.metatitle ? page.metatitle : parent() -}}{% endblock %}
{% block og_descr %}{{- page.metadescription ? page.metadescription : parent() -}}{% endblock %}
{% block last_updated_block %}{{ page.updatedAtDatetime }}{% endblock %}

{% block bodyId %}about{% endblock %}

{% block content %}
{% include "AppBundle:App:tmate.list.menu.html.twig" with {'back': 'app_about_us'} %}

<wrapper>
  <section id="personal-info">
    <div class="container">
      <div class="side a">
        <div id="persona-front">
          <img src="/img/persona/persona.png"  alt="{{ attorney.name }}">
          {#
          <img src="{{ asset(attorney.photoFullPath) }}" alt="{{ attorney.name }}">
          #}
        </div>
        <div class="statistic">
          <ul>
            <li>
              <span>233</span>
              <h5>Completed Casess</h5>
            </li>
            <li>
              <span>33</span>
              <h5>Years of practice</h5>
            </li>
            <li>
              <span>97%</span>
              <h5>wining rate</h5>
            </li>
          </ul>
        </div>
      </div>
      <div class="side b">

  			{% include "default/breadcrumbs.html.twig" with { 'elements': { 0: {'url': "app_about_us", 'name': "About us" }}, 'currentPage': attorney.name, 'home' : false } %}

        <h2>{{ attorney.name }}</h2>
        <h4>type something</h4>

        {% include "default/social_block.html.twig" %}
        {{ attorney.description | raw }}

      </div>
    </div>
  </section>

  <section id="team-show">
    <div class="container">
      <div class="_text">
        <h2>our team</h2>
      </div>
      <!-- <div class="pslider">
        <ul class='slides a'>
          <li class='cur'>

          </li>
          <li>

          </li>
        </ul>
        <div class="cntrls noselect">
          <a href="javascript:void(0);"><div class="prev cntrl"></div></a>
          <a href="javascript:void(0);"><div class="next cntrl"></div></a>
        </div>
      </div> -->

      <ul class='team'>
        {#
        {% for teammate in attorneys %}
        <li>
          <a href="{{ teammate.url }}"><img src="{{ asset(teammate.photoFullPath) }}"></a>
          <div class="block">
            <h3>{{ teammate.name }}</h3>
            <div class="info-block">
              <h4>Type something</h4>
              <p>
                People like a “special” price or exclusive offer directed
              </p>
            </div>
            <div class="stat-block">
              <h4><a href="{{ teammate.url }}">Click to discover</a></h4>
              <div class="statistic">
                <ul>
                  <li>
                    <span>233</span>
                    <h5>Completed Casess</h5>
                  </li>
                  <li>
                    <span>33</span>
                    <h5>Years of practice</h5>
                  </li>
                  <li>
                    <span>97%</span>
                    <h5>wining rate</h5>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </li>
      {% endfor %}
      #}
        <li>
          <a href="#"><img src="/img/persona/per-w.png"></a>
          <div class="block">
            <h3>Nettie Norton</h3>
            <div class="info-block">
              <h4>Type something</h4>
              <p>
                People like a “special” price or exclusive offer directed
              </p>
            </div>
            <div class="stat-block">
              <h4><a href="">Click to discover</a></h4>
              <div class="statistic">
                <ul>
                  <li>
                    <span>233</span>
                    <h5>Completed Casess</h5>
                  </li>
                  <li>
                    <span>33</span>
                    <h5>Years of practice</h5>
                  </li>
                  <li>
                    <span>97%</span>
                    <h5>wining rate</h5>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </li>
        <li>
          <a href="#"><img src="/img/persona/per-m.png"></a>
          <div class="block">
            <h3>Henry Harper</h3>
            <div class="info-block">
              <h4>Type something</h4>
              <p>
                People like a “special” price or exclusive offer directed
              </p>
            </div>
            <div class="stat-block">
              <h4><a href="">Click to discover</a></h4>
              <div class="statistic">
                <ul>
                  <li>
                    <span>233</span>
                    <h5>Completed Casess</h5>
                  </li>
                  <li>
                    <span>33</span>
                    <h5>Years of practice</h5>
                  </li>
                  <li>
                    <span>97%</span>
                    <h5>wining rate</h5>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </li>
        <li>
          <a href="#"><img src="/img/persona/per-w.png"></a>
          <div class="block">
            <h3>Nettie Norton</h3>
            <div class="info-block">
              <h4>Type something</h4>
              <p>
                People like a “special” price or exclusive offer directed
              </p>
            </div>
            <div class="stat-block">
              <h4><a href="">Click to discover</a></h4>
              <div class="statistic">
                <ul>
                  <li>
                    <span>233</span>
                    <h5>Completed Casess</h5>
                  </li>
                  <li>
                    <span>33</span>
                    <h5>Years of practice</h5>
                  </li>
                  <li>
                    <span>97%</span>
                    <h5>wining rate</h5>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </li>
        <li>
          <a href="#"><img src="/img/persona/per-n.svg"></a>
          <div class="block">
            <h3>Nettie Norton</h3>
            <div class="info-block">
              <h4>Type something</h4>
              <p>
                People like a “special” price or exclusive offer directed
              </p>
            </div>
            <div class="stat-block">
              <h4><a href="">Click to discover</a></h4>
              <div class="statistic">
                <ul>
                  <li>
                    <span>233</span>
                    <h5>Completed Casess</h5>
                  </li>
                  <li>
                    <span>33</span>
                    <h5>Years of practice</h5>
                  </li>
                  <li>
                    <span>97%</span>
                    <h5>wining rate</h5>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>


  </section>
  <section id="contact-baner">
    <div class="back">
      <div class="cover"></div>
    </div>
      <div class="container">
        <div class="side a">
          <a href="app_dev.php"><img src="/img/lgog.svg"></a>
          <h3>
            Working In Your <br>
            Best Interests Every <br>
            Step Of The Way
          </h3>
        </div>
        <div class="side b">
      				{% include "AppBundle:Contact:contact_block_form.html.twig" %}
          <!-- <div id="contactus">
            <h2>Contact us now</h2>
            <p>Leave your message in the form below</p>
            <form action="">
              <div class="form-data">
                <lable class='action'>name</lable>
                <input type="text" name='name'>
              </div>
              <div class="form-data input">
                <lable class='action'>email</lable>
                <input type="text" name='name'>
              </div>
              <div class="form-data input">
                <lable class='action'>phone</lable>
                <input type="text" name='name'>
              </div>
              <div class="form-data">
                <lable>message</lable>
                <textarea name="msg" placeholder='Tell us about your case'></textarea>
              </div>

              <a href=""><div class="pbtn">contact us</div></a>
            </form>
          </div> -->
        </div>
      </div>
  </section>
</wrapper>
{% endblock %}

src/AppBundle/Resources/views/App/avvo.html.twig
<ul class='slides b'>
    <li class='cur'>
			<img class="avvo_img" src="/images/avvo/avvo01.png" alt="Top Divorce Attorney Yelena Sharova">
		</li>
		<li>
			<img class="avvo_img" src="/images/avvo/avvo02.png" alt="Top Criminal Defense Attorney Yelena Sharova">
		</li>
		<li>
			<img class="avvo_img" src="/images/avvo/avvo03.png" alt="Top Divorce Attorney New York">
		</li>
		<li>
			<img class="avvo_img" src="/images/avvo/avvo04.png" alt="Top Criminal Defense Attorney New York">
		</li>
		<li>
			<img class="avvo_img" src="/images/avvo/avvo05.png" alt="Top Divorce Lawyer New York">
		</li>
		<li>
			<img class="avvo_img" src="/images/avvo/avvo06.png" alt="Top Criminal Defense Lawyer New York">
		</li>
</ul>

src/AppBundle/Resources/views/App/bar_association_block.html.twig
{% block contactSection %}
  {{ barAssociationBlock.content | raw }}
{% endblock %}

src/AppBundle/Resources/views/App/index.html.twig
{% extends 'AppBundle::layout.html.twig' %}

{% block title %}{{- page.metatitle ? page.metatitle : parent() -}}{% endblock %}
{% block meta_keywords %}{{- page.metakeywords ? page.metakeywords : parent() -}}{% endblock %}
{% block meta_description %}{{- page.metadescription ? page.metadescription : parent() -}}{% endblock %}
{% block og_title %}{{ og_title }}{% endblock %}
{% block og_descr %}{{ og_descr }}{% endblock %}
{% block last_updated_block %}{{ page.updatedAtDatetime}}{% endblock %}

{% block content %}

		<wrapper>

      {% include "AppBundle:App:main-mozaic.html.twig" %}

      {# STATIC HTML #}
      {% include "AppBundle:App:main.static.html.twig" %}

 			{% render controller("PluginsPracticAreaBundle:PracticArea:practicAreasShortList") %}

 			{% render controller("PluginsNewsBundle:News:lastMozaicList") %}

 			{% if not blogDisable %}
 					{% block blogSection %}
 					<section class="contact-section content-row clearfix">
 							<!-- <h2 id="h2-blog">Blog</h2> -->
 							{% render controller("PluginsBlogBundle:Blog:short") %}
 					</section>
 					{% endblock %}
 			{% endif %}
 		</wrapper>

		{#
		{% include "AppBundle:App:main_old.html.twig" %}
		 #}

{% endblock %}
{% block footer %}
		{% include "default/footer.html.twig" with {'home' : true} %}
{% endblock %}

src/AppBundle/Resources/views/App/main_old.html.twig
{% block slideShow %}
<section class="slide-show-container">
		<section class="slide-show">
				<!-- <div class="element slide01" style="width: 1000px;">
						<span>
								clients come first
						</span>
				</div> -->
				<div class="element slide02" style="width: 1000px;">
						<span>
								power<br/>
								precision<br/>
								professionalism
						</span>
				</div>
				<div class="element slide03" style="width: 1000px;">
						<span>
								details matter
						</span>
				</div>
				<div class="element slide04" style="width: 1000px;">
						<span>
								dedicated<br/>
								and experienced<br/>
								attorneys at your service
						</span>
				</div>
				<div class="element slide05" style="width: 1000px;">
						<span>
								we think<br/>
								outside the box
						</span>
				</div>
		</section>
		<div class="slide-left"></div>
		<div class="slide-right"></div>
</section>
{% endblock %}

{% render controller("PluginsPracticAreaBundle:PracticArea:practicAreasShortList") %}

{% block avvo %}
<section class="avvo-section clearfix hidden">
		{% include "AppBundle:App:avvo.html.twig" %}
</section>
{% endblock %}

{% render controller("PluginsNewsBundle:News:lastShortList") %}

{% block contactSection %}
<section class="contact-section content-row clearfix">
		<div class="text-containter">
				<h2 class="title">{{ whyUsBlock.name }}</h2>
				{{ whyUsBlock.content | raw }}
		</div>
		{% render controller("AppBundle:Contact:form") %}
</section>
{% endblock %}

{% block greatQuotes %}
<section class="great-quotes">
		<div class="content-box">
				<h2 id="h2-test">Testimonials</h2>
				<div class="content clearfix">
				{% for quote in quotes %}
						<div class="quote" style="width: 850px;">
								<span class="quote-text">
										{{ quote.quoteS | raw }}
								</span>
								<span class="author">
										{{ quote.nameS  | raw }}
								</span>
						</div>
						{% endfor %}
				</div>
				<div class="slide-left"></div>
				<div class="slide-right"></div>
		</div>
</section>
{% endblock %}

{% if not blogDisable %}
		{% block blogSection %}
		<section class="contact-section content-row clearfix">
				<!-- <h2 id="h2-blog">Blog</h2> -->
				{% render controller("PluginsBlogBundle:Blog:short") %}
		</section>
		{% endblock %}
{% endif %}

{% block barAssociationsBlock %}
<section class="bar-association-section clearfix {{ not blogDisable ? "highlighted" }}">
		{% render controller("AppBundle:App:barAssociationBlock") %}
</section>


{% endblock %}
<script type="text/javascript">
$(document).ready(function(){
		$(".avvo-section").removeClass("hidden");
});
</script>