src/Plugins/BlogBundle/Entity/BlogPost.php
<?php
namespace Plugins\BlogBundle\Entity;

use AppBundle\Entity\BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="Plugins\BlogBundle\Repository\BlogPostRepository")
 * @ORM\Table(name="BlogPost",
 *     uniqueConstraints={@ORM\UniqueConstraint(name="url_uniq", columns={"url"})},
 *     indexes={@ORM\Index(name="fk_BlogPost_blog_category_id_idx", columns={"blog_category_id"})},
 *     indexes={@ORM\Index(name="fk_BlogPost_blog_topic_id_idx", columns={"blog_topic_id"})}
 * )
 */
class BlogPost extends BaseEntity
{

    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var BlogCategory
     *
     * @ORM\ManyToOne(targetEntity="BlogCategory")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="blog_category_id", referencedColumnName="id")
     * })
     */
    protected $blogCategory;

    /**
     * @var BlogTopic
     *
     * @ORM\ManyToOne(targetEntity="BlogTopic")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="blog_topic_id", referencedColumnName="id")
     * })
     */
    protected $blogTopic;

    /**
     * @ORM\Column(name="name", type="string", length=256)
     */
    protected $name;

    /**
     * @ORM\Column(name="short", type="text")
     */
    protected $short;

    /**
     * @ORM\Column(name="short_home", type="text")
     */
    protected $short_home;

    /**
     * @ORM\Column(name="content", type="text")
     */
    protected $content;

    /**
		* @ORM\Column(name="amp_content", type="text")
		*/
		 protected $ampContent;

		 /**
     * @ORM\Column(name="url", type="string", length=255)
     */
    protected $url;

    /**
     * @ORM\Column(name="metatitle", type="text", nullable=true)
     */
    protected $metatitle;

    /**
     * @ORM\Column(name="metadescription", type="text", nullable=true)
     */
    protected $metadescription;

    /**
     * @ORM\Column(name="metakeywords", type="text", nullable=true)
     */
    protected $metakeywords;

    /**
     * @ORM\Column(name="is_popular", type="boolean", nullable=true)
     */
    protected $is_popular;

    /**
     * @ORM\Column(name="public_at", type="datetime")
     */
    protected $public_at;

    protected $public_at_with_random_time;

    /**
     * @return string
     */
    public function getDateUsFormat()
    {
        return $this->getPublicAt()->format('dS F Y - h:i A');
    }

    /**
     * @return string
     */
    public function getCreatedUsFormat()
    {
        return $this->getCreatedAt()->format('dS F Y - h:i A');
    }

    /**
     * @return bool
     */
    public function isShown()
    {
        return $this->getPublicAt() <= (new \DateTime());
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return BlogPost
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set short
     *
     * @param string $short
     * @return BlogPost
     */
    public function setShort($short)
    {
        $this->short = $short;

        return $this;
    }

    /**
     * Get short
     *
     * @return string
     */
    public function getShort()
    {
        return $this->short;
    }

    /**
     * Set short_home
     *
     * @param string $shortHome
     * @return BlogPost
     */
    public function setShortHome($shortHome)
    {
        $this->short_home = $shortHome;
    }

    /**
     * Get short_home
     *
     * @return string
     */
    public function getShorthome()
    {
        return $this->short_home;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return BlogPost
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

		/**
     * Set content
     *
     * @param string $ampContent
     * @return PracticArea
     */
    public function setAmpContent($ampContent)
    {
        $this->ampContent = $ampContent;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */ 
    public function getAmpContent()
    {
        return $this->ampContent;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return BlogPost
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set metatitle
     *
     * @param string $metatitle
     * @return BlogPost
     */
    public function setMetatitle($metatitle)
    {
        $this->metatitle = $metatitle;

        return $this;
    }

    /**
     * Get metatitle
     *
     * @return string
     */
    public function getMetatitle()
    {
        return $this->metatitle;
    }

    /**
     * Set metadescription
     *
     * @param string $metadescription
     * @return BlogPost
     */
    public function setMetadescription($metadescription)
    {
        $this->metadescription = $metadescription;

        return $this;
    }

    /**
     * Get metadescription
     *
     * @return string
     */
    public function getMetadescription()
    {
        return $this->metadescription;
    }

    /**
     * Set metakeywords
     *
     * @param string $metakeywords
     * @return BlogPost
     */
    public function setMetakeywords($metakeywords)
    {
        $this->metakeywords = $metakeywords;

        return $this;
    }

    /**
     * Get metakeywords
     *
     * @return string
     */
    public function getMetakeywords()
    {
        return $this->metakeywords;
    }

    /**
     * Set blogCategory
     *
     * @param \Plugins\BlogBundle\Entity\BlogCategory $blogCategory
     * @return BlogPost
     */
    public function setBlogCategory(\Plugins\BlogBundle\Entity\BlogCategory $blogCategory = null)
    {
        $this->blogCategory = $blogCategory;

        return $this;
    }

    /**
     * Get blogCategory
     *
     * @return \Plugins\BlogBundle\Entity\BlogCategory
     */
    public function getBlogCategory()
    {
        return $this->blogCategory;
    }

    /**
     * Set blogTopic
     *
     * @param \Plugins\BlogBundle\Entity\BlogTopic $blogTopic
     * @return BlogPost
     */
    public function setBlogTopic(\Plugins\BlogBundle\Entity\BlogTopic $blogTopic = null)
    {
        $this->blogTopic = $blogTopic;

        return $this;
    }

    /**
     * Get blogTopic
     *
     * @return \Plugins\BlogBundle\Entity\BlogTopic
     */
    public function getBlogTopic()
    {
        return $this->blogTopic;
    }

    /**
     * Set is_popular
     *
     * @param boolean $isPopular
     * @return BlogPost
     */
    public function setIsPopular($isPopular)
    {
        $this->is_popular = $isPopular;

        return $this;
    }

    /**
     * Get is_popular
     *
     * @return boolean
     */
    public function getIsPopular()
    {
        return $this->is_popular;
    }

    /**
     * Set public_at
     *
     * @param \DateTime $publicAt
     * @return BlogPost
     */
    public function setPublicAt($publicAt)
    {
        $this->public_at = $publicAt;

        return $this;
    }

    /**
     * Get public_at
     *
     * @return \DateTime
     */
    public function getPublicAt()
    {
        return empty($this->public_at) ? new \DateTime() : $this->public_at;
    }

    /**
     * @param \DateTime $publicAtWithRandomTime
     * @return $this
     */
    public function setPublicAtWithRandomTime($publicAtWithRandomTime) {
        $this->public_at_with_random_time = $publicAtWithRandomTime;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getPublicAtWithRandomTime() {
        return $this->public_at_with_random_time;
    }
}

src/Plugins/BlogBundle/Controller/BlogController.php
<?php

namespace Plugins\BlogBundle\Controller;

use Doctrine\ORM\NoResultException;
use Plugins\BlogBundle\Entity\BlogCategory;
use Plugins\BlogBundle\Entity\BlogTopic;
use Plugins\ContentBundle\Entity\Content;
use AppBundle\Controller\BaseController;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
class BlogController extends BaseController
{
    const NUMBER_LAST_POSTS_ON_HOMEPAGE = 5;
    const LIMIT_SHOW_POSTS = 10;
    const LIMIT_MOZAIC_ITEMS = 1;

    /**
     * Homepage action
     *
     * @param string $categoryUrl
     * @param string $topicUrl
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws NotFoundHttpException
     */
    public function indexAction(Request $request, $categoryUrl = null, $topicUrl = null)
    {
        $category = null;
        $topic = null;

        $page = (int)$request->get('page', 1);
        $phrases = $request->get('q', null);
        $offset = ($page > 1) ? self::LIMIT_SHOW_POSTS * ($page - 1) : 0;
        $route = 'plugins_blog_homepage';
        $parameters = array();

        if (!empty($categoryUrl)) {
            /** @var BlogCategory $category */
            $content = $category = $this->getBlogCategoryRepository()->findOneByUrl($categoryUrl);
            if (empty($category)) {
                throw new NotFoundHttpException();
            }
            $route = 'plugins_blog_view_category';
            $parameters['categoryUrl'] = $category->getUrl();
            if (!empty($topicUrl)) {
                /** @var BlogTopic $topic */
                $content = $topic = $this->getBlogTopicRepository()->findOneByUrl($topicUrl);
                if (empty($topic)) {
                    throw new NotFoundHttpException();
                }
                $route = 'plugins_blog_view_topic';
                $parameters['topicUrl'] = $category->getUrl();
            }
            $phrases = null;
        } else {
            $content = $this->getContentRepository()->findOneByKey(Content::CONTENT_BLOG_HOMEPAGE);
        }

        if (!empty($topic) && $topic->getBlogCategory()->getId() != $category->getId()) {
            throw new NotFoundHttpException();
        }

        $posts = $this->getBlogPostRepository()->findPosts(self::LIMIT_SHOW_POSTS, $offset, $category, $topic, $phrases);
        $allposts = $this->getBlogPostRepository()->findAllPosts($offset, $category, $topic, $phrases);
        $count = $this->getBlogPostRepository()->countPosts($category, $topic, $phrases);
        $pages = (int)ceil($count / self::LIMIT_SHOW_POSTS);
				$postname = 0;
				$hometrig = true;

        return $this->render('PluginsBlogBundle:Blog:index.html.twig', array(
            'category' => $category,
            'topic' => $topic,
            'content' => $content,
            'posts' => $posts,
            'allposts' => $allposts,
            'page' => $page,
            'pages' => $pages,
            'queries' => $phrases,
            'route' => $route,
            'parameters' => $parameters,
						'postname' => $postname,
						'hometrig' => $hometrig
        ));
    }

    /**
     * Render vertical menu block of blog
     *
     * @param integer $categoryId
     * @param integer $topicId
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function blogVerticalMenuAction($categoryId = 0, $topicId = 0, $home = false, $name = 0)
    {

        $elements = $this->getBlogCategoryRepository()->findCategory();

        return $this->render('PluginsBlogBundle:Blog:vertical_menu.html.twig', array(
            'elements' => $elements,
            'categoryId' => $categoryId,
            'topicId' => $topicId,
						'home' => $home,
						'name' => $name
        ));
    }

    /**
     * Render popular posts
     */
    public function popularPostsAction()
    {
        $posts = $this->getBlogPostRepository()->findPopularPosts(self::NUMBER_LAST_POSTS_ON_HOMEPAGE);
        return $this->render('PluginsBlogBundle:Blog:popular_posts.html.twig', array(
            'posts' => $posts,
        ));
    }

    /**
     * View post action
     *
     * @param string $categoryUrl
     * @param string $topicUrl
     * @param string $postUrl
     * @param integer $id
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function viewPostAction($categoryUrl, $topicUrl = null, $postUrl, $id)
    {
        try {
            $post = $this->getBlogPostRepository()->findPost($id);
        } catch (NoResultException $e) {
            throw new NotFoundHttpException();
        }

				if ($this->isAmp()) {
					if (empty($post->getAmpContent())) {
						throw new NotFoundHttpException();
					}
					$template = 'amp_view_post.html.twig';
				} else {
					$template = 'view_post.html.twig';
				}
				return $this->render('PluginsBlogBundle:Blog:' . $template, array(
            'post' => $post
        ));
    }


    /**
     * Render blog block to homepage
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function shortAction()
    {
        $categories = $this->getBlogCategoryRepository()->findCategory();

        return $this->render('PluginsBlogBundle:Blog:short.html.twig', array(
            'categories' => $categories
        ));
    }


    /**
     * Render mozaic items
     */
    public function blogMozaicItemsAction($catreq = null) {
			$categories = $this->getBlogCategoryRepository()->findCategory();
			$category = $this->getBlogCategoryRepository()->findOneByUrl($catreq);
			$posts = $this->getBlogPostRepository()->findPosts(self::LIMIT_MOZAIC_ITEMS, 0, $category);

      return $this->render('PluginsBlogBundle:Blog:main-mozaic-blog-item.html.twig', array(
              'posts'   => $posts,
							'categories' => $categories,
	            'category' => $category
          ));
    }
    // pointer post search
    public function blogPostAction() {
      $request = $this->getRequest();
      $requestString = $request->get('searchText');

      $entities = $this->getBlogPostRepository()->findByString($requestString);
      $en_filtr =  \Doctrine\Common\Util\Debug::export($entities,4);

      foreach($en_filtr as $e){
        $id = $e->blogCategory->id;
        $parent = $this->getBlogCategoryRepository()->findById( $id );
        $par_filtr =  \Doctrine\Common\Util\Debug::export($parent[0],3);
        $e->short_home = $par_filtr->url;
      }

      return new Response(json_encode($en_filtr));
      // return new Response(($en_filtr));
    }
}

src/Plugins/BlogBundle/Resources/views/Blog/cat_name.html.twig
{% block catName %}
    {{ currentPage }}
    {% if (pages > 1) %}
      {% if (page != 1) %}
        -&nbsp;Page&nbsp;{{ page }}
      {% endif %}
    {% endif %}
{% endblock %}

src/Plugins/BlogBundle/Resources/views/Blog/index.html.twig
{% extends 'AppBundle::layout.html.twig' %}

{% block title %}{{- content.metatitle ? content.metatitle : parent() -}}{% include "PluginsBlogBundle:Blog:page_to_meta.html.twig" with {'pages': pages, 'page': page} %}{% endblock %}
{% block meta_keywords %}{{- content.metakeywords ? content.metakeywords : parent() -}}{% endblock %}
{% block meta_description %}{{- content.metadescription ? content.metadescription : parent() -}}{% include "PluginsBlogBundle:Blog:page_to_meta.html.twig" with {'pages': pages, 'page': page} %}{% endblock %}
{% block og_title %}{{- content.metatitle ? content.metatitle : parent() -}}{% include "PluginsBlogBundle:Blog:page_to_meta.html.twig" with {'pages': pages, 'page': page} %}{% endblock %}
{% block og_descr %}{{- content.metadescription ? content.metadescription : parent() -}}{% endblock %}
{% block last_updated_block %}{{ content.updatedAtDatetime}}{% endblock %}

{% block canonicalLinkBlock %}
{# include "default/canonical.html.twig" #}
{% set np_params = null %}
{% if queries %}
		{% set params = {'q' : queries|url_encode} %}
{% endif %}
{% include "default/next-prev.html.twig" with {'pages': pages, 'page': page, 'np_params': parameters, 'queries': np_params, 'route': route, 'limit': null} %}
{% endblock %}

{% block bodyId %}blog{% endblock %}
{% block bodyClass %}blog{% endblock %}

{% block content %}
<wrapper>
		<section id="blog" class="parent container-fluid">
				<div class="row">
						<div class="submenu">

							<div id="side_menu">

								{% if posts is empty %}

								{% else %}

									{% for post in posts %}
										{% if category is empty %}
											{% set postname = 'Blog' %}
											{% set hometrig = true %}
										{% else %}
											{% set postname = category.name %}
											{% set hometrig = true %}
										{% endif %}
									{% endfor %}
									{% if hometrig == true %}
										<h1>{{ postname }} {% include "PluginsBlogBundle:Blog:page_to_name.html.twig" with {'pages': pages, 'page': page} %}</h1>
									{% else %}
									  <h2>{{ postname }} {% include "PluginsBlogBundle:Blog:page_to_name.html.twig" with {'pages': pages, 'page': page} %}</h2>
									{% endif %}

									<div class="psearch">
											<input type="text" id='search'>
											<!-- <i class="fa fa-search" aria-hidden="true"></i> -->
											<img class="s_pbtn" src="/img/s-icon.svg" alt="">
									</div>

									{# {% include "PluginsBlogBundle:Blog:search_form.html.twig" with { 'queries': queries } %} #}
									<!-- QUERRIES!!! -->

									{% render controller("PluginsBlogBundle:Blog:blogVerticalMenu", {categoryId: category ? category.id : null, topicId: topic ? topic.id : null, home : hometrig, name : postname }) %}

								{% endif %}
								<!-- {% include "PluginsPracticAreaBundle:PracticArea:google_map_pa.html.twig" %} -->
							</div>
							<div class="fb-square">{% include 'default/fb-square.html.twig' %}</div>
						</div>
<!-- _________________ -->
								{% include "PluginsBlogBundle:Blog:show_blog.html.twig" with {
								'category' : category,
								'queries' : queries,
								'pages' : pages,
								'topic' : topic,
								'posts' : posts,
								'allposts' : allposts
								}%}
<!-- _________________ -->
						<!--  -->
						{#
						<div class="content">
							{% if category is empty %}
									{% if queries is empty %}
											{% include "default/breadcrumbs.html.twig" with { 'currentPage': 'Blog', 'elements': null, 'home' : false } %}
									{% else %}
											{% include "default/breadcrumbs.html.twig" with { 'currentPage': queries, 'elements':
													{
															0: {'url': "plugins_blog_homepage", 'name': "Blog" },
													}, 'home' : false
											} %}
									{% endif %}

									<!-- <h1 id="blog-h1">Blog {% include "PluginsBlogBundle:Blog:page_to_name.html.twig" with {'pages': pages, 'page': page} %}</h1> -->

							{% elseif topic is empty %}
									{% include "default/breadcrumbs.html.twig" with { 'currentPage': category.name, 'elements':
													{
															0: {'url': "plugins_blog_homepage", 'name': "Blog" },
													}, 'home' : false
											} %}
									<!-- <h1 id="blog-h1">{% include "PluginsBlogBundle:Blog:cat_name.html.twig" with { 'currentPage': category.name } %}</h1> -->
							{% else %}
									{% include "default/breadcrumbs.html.twig" with { 'currentPage': topic.name, 'elements':
													{
															0: {'url': "plugins_blog_homepage", 'name': "Blog" },
															1: {'url': "plugins_blog_view_category", 'name': category.name, 'params': {'categoryUrl' : category.url}},
													}, 'home' : false
											} %}
									{% include "PluginsBlogBundle:Blog:cat_name.html.twig" with { 'currentPage': category.name, 'elements':
													{
															0: {'url': "plugins_blog_homepage", 'name': "Blog" },
													}
									} %}
									<!-- <h1 id="blog-h1">{% include "PluginsBlogBundle:Blog:cat_name.html.twig" with { 'currentPage': category.name } %}</h1> -->
							{% endif %}

								<div class="list">

								{% if category is empty %}

								{% set previews = {
												0: "Criminal defense",
												1: "Family law",
												2: "Civil litigation"
								} %}

								{% if posts is empty %}
										<div class="blog-subtitle">No posts found</div>
								{% else %}
									{% set break = false %}
										{% for step in 0..2 %}
											<div class="blog-subtitle">
												{{previews[step]}} latest posts
											</div>
											{% set break = false %}
											{% set count = 0 %}
											<ul>
												{% for post in allposts if not break %}
													{% if post.blogTopic is empty %}
															{% set postUrl = path("plugins_blog_view_post_without_topic", {categoryUrl: post.blogCategory.url, id: post.id, postUrl: post.url}) %}
													{% else %}
															{% set postUrl = path("plugins_blog_view_post", {categoryUrl: post.blogCategory.url, topicUrl: post.blogTopic.url, id: post.id, postUrl: post.url}) %}
													{% endif %}
													{% if post.blogCategory.name == previews[step] %}
															<li class="item">
																<a href="{{ postUrl }}" title="{{ post.name }}"><h3>{{ post.name }}</h3></a>
																<div class="short">
																	{{ post.short | raw }}
																</div>
																<hr>
																<div class="info">
																	<div class="row">
																		<div class="dc">
																			<div class="pattr"><span>date:</span>{{ post.dateUsFormat }}</div>
																			<div class="pattr"><span>category:</span>{{ post.blogCategory.name }}</div>
																		</div>
																		<div class="readmore"><a href="{{ postUrl }}"><span class="pbtn">read more</span></a></div>
																	</div>
																</div>
															</li>
															{% set count = count + 1 %}
															{% if count == 5 %}
																{% set break = true %}
															{% endif %}
													{% endif %}
												{% endfor %}
											</ul>
										{% endfor %}
								{% endif %}

								{% else %}

									{% if posts is empty %}
										<div class="blog-subtitle">No posts found</div>
									{% else %}
										<ul>
										{% for post in posts %}
												{% if post.blogTopic is empty %}
													{% set postUrl = path("plugins_blog_view_post_without_topic", {categoryUrl: post.blogCategory.url, id: post.id, postUrl: post.url}) %}
												{% else %}
													{% set postUrl = path("plugins_blog_view_post", {categoryUrl: post.blogCategory.url, topicUrl: post.blogTopic.url, id: post.id, postUrl: post.url}) %}
												{% endif %}
					              <li class="item">
					                <a href="{{ postUrl }}" title="{{ post.name }}"><h3>{{ post.name }}</h3></a>
					                <div class="short">
					                  {{ post.short | raw }}
					                </div>
					                <hr>
					                <div class="info">
					                  <div class="row">
															<div class="dc">
																<div class="pattr"><span>date:</span>{{ post.dateUsFormat }}</div>
							                  <div class="pattr"><span>category:</span>{{ post.blogCategory.name }}</div>
															</div>
						                  <div class="readmore"><a href="{{ postUrl }}"><span class="pbtn">read more</span></a></div>
														</div>
					                </div>
					              </li>
										{% endfor %}
				            </ul>
									{% endif %}

								{% endif %}

								{% if category is not empty %}

								{% set params = null %}
								{% if queries %}
										{% set params = {'q' : queries|url_encode} %}
								{% endif %}
								{% include "AppBundle:App:pagination.html.twig" with {'pages': pages, 'page': page, 'params': parameters, 'queries': params, 'route': route, 'limit': null} %}
								{% endif %}
								</div>
						</div>
						<!--  -->
						#}
						<div class="contactus">
								{% include "AppBundle:Contact:contact_block_form.html.twig" %}
								<div class="fb-square">{% include 'default/fb-square.html.twig' %}</div>
						</div>
				</div>
		</section>
</wrapper>
{% endblock %}

src/Plugins/BlogBundle/Resources/views/Blog/short.html.twig
{% block shortBlog %}
<section id='p_blog' class="parent">
		<div class="submenu">
			<div id="side_menu">
				<h2>Blog</h2>
				{#
				{% include "PluginsBlogBundle:Blog:search_form.html.twig" with { 'queries': null } %}
				#}

				<div class="psearch">
						<input type="text" id='search'>
						<!-- <i class="fa fa-search" aria-hidden="true"></i> -->
						<img class="s_pbtn" src="/img/s-icon.svg" alt="">
				</div>
				{% include "PluginsBlogBundle:Blog:search.ajax.html.twig" %}

				<ul class="blogShortList">
					{% for category in categories %}

							<li class="short-blog-link link {{ loop.first ? 'focus' }}" id="{{ loop.index }}">
								<span class="link-short">{{ category.name }}</span>
							</li>

					{% endfor %}
        </ul>
			</div>
		</div>
		<div class="content">
			<div  id='static-show'>
		<!-- _________________ -->
			{% for category in categories %}
			{% set break = 1 %}
			<ul class="short-blog-category category {{ not loop.first ? 'hidden' }}" id="{{ loop.index }}-details">
			<div class="crumbs">
				<h2>{{category}}</h2>
			</div>

				{% for post in category.blogPosts if break %}
						{% if post.shown %}
								{% if post.blogTopic is empty %}
										{% set postUrl = path("plugins_blog_view_post_without_topic", {categoryUrl: post.blogCategory.url, id: post.id, postUrl: post.url}) %}
								{% else %}
										{% set postUrl = path("plugins_blog_view_post", {categoryUrl: post.blogCategory.url, topicUrl: post.blogTopic.url, id: post.id, postUrl: post.url}) %}
								{% endif %}
										<li class="item {{ loop.first ? "first" }} {{ (loop.index == 15) or (loop.index == category.blogPosts | length) ? "last" }}">
											<h3><a href="{{ postUrl }}" title="{{ post.name }}">{{ post.name }}</a></h3>
											<p>
												{% if post.shortHome is empty %}
													{% set x = 0 %}
													{% set text = post.short | split('.') %}
														{% for t in text %}
																{% set x = (x + t|length) %}
																{% if (x) < 450 %}
																	{% if (t|last == '.') or (t|last == ' ') or (t|last == '>') %}
																		{{ t | raw }}
																	{% else %}
																		{{ t | raw }}.
																	{% endif %}
																{% endif %}
														{% endfor %}
												{% else %}
													{{ post.shortHome | raw }}
												{% endif %}
											</p>
											<hr>
											<div class="info">
							          <div class="row">
							            <div class="dc">
							              <div class="pattr"><span>date:</span>{{ post.dateUsFormat }}</div>
														<div class="pattr"><span>category:</span>{{ category }}</div>
							            </div>
							            <div class="readmore"><a href="{{ postUrl }}"><span class="pbtn">read more</span></a></div>
							          </div>
							        </div>
										</li>
										{% if loop.index == 15 %}
												{% set break = 0 %}
										{% endif %}
								{% endif %}
						{% endfor %}

			</ul>
			{% endfor %}
			<a href="{{ path('plugins_blog_homepage') }}"><p class='ptext'>Link to full Blog page</p></a>
			<!-- _________________ -->
			  </div>
			<!-- _________________ -->
			    <div class="list" id="blog-filtered">
			      <ul id='search_show'>
			      </ul>
			    </div>
			<!-- _________________ -->
		</div>


		<div class="contactus">
				{% include "AppBundle:Contact:contact_block_form.html.twig" %}
				<div class="fb-square">{% include 'default/fb-square.html.twig' %}</div>
		</div>

    <script type="text/javascript">
			console.log('azaza');
					console.log('ururu');
            $(".short-blog-link").click(function () {
                var self = this,
                        id = $(self).attr("id");
												console.log("#" + id);
                $(".short-blog-category").addClass("hidden");
                $(".short-blog-link").removeClass("focus");

                $("#" + id + "-details").removeClass("hidden");
                $("#" + id).addClass("focus");
            });
    </script>

</section>
{% endblock %}