src/Plugins/NewsBundle/Entity/News.php
<?php
// src/Plugins/NewsBundle/Entity/News.php
namespace Plugins\NewsBundle\Entity;
use AppBundle\Entity\BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="Plugins\NewsBundle\Repository\NewsRepository")

 * @ORM\Table(name="News", uniqueConstraints={@ORM\UniqueConstraint(name="url_uniq", columns={"url"})})
 */
class News extends BaseEntity {

    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="name", type="string", length=500)
     */
    protected $name;

    /**
     * @ORM\Column(name="short", type="text")
     */
    protected $short;

    /**
     * @ORM\Column(name="content", type="text")
     */
    protected $content;

    /**
     * @ORM\Column(name="metatitle", type="text", nullable=true)
     */
    protected $metatitle;

    /**
     * @ORM\Column(name="metadescription", type="text", nullable=true)
     */
    protected $metadescription;

    /**
     * @ORM\Column(name="metakeywords", type="text", nullable=true)
     */
    protected $metakeywords;

    /**
     * @ORM\Column(name="public_at", type="datetime")
     */
    protected $public_at;

    /**
     * @ORM\Column(name="url", type="string", length=255)
     */
    protected $url;

    public function getShortSimpleText() {
        $short = strip_tags($this->getShort());

        return $short;
    }

    public function getDateUsFormat() {
        return $this->getPublicAt()->format('dS F Y - h:i A');
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set short
     *
     * @param string $short
     * @return News
     */
    public function setShort($short)
    {
        $this->short = $short;

        return $this;
    }

    /**
     * Get short
     *
     * @return string
     */
    public function getShort()
    {
        return $this->short;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return News
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set metatitle
     *
     * @param string $metatitle
     * @return News
     */
    public function setMetatitle($metatitle)
    {
        $this->metatitle = $metatitle;

        return $this;
    }

    /**
     * Get metatitle
     *
     * @return string
     */
    public function getMetatitle()
    {
        return str_replace(array("\n","\r"), ' ', $this->metatitle);
    }

    /**
     * Set metadescription
     *
     * @param string $metadescription
     * @return News
     */
    public function setMetadescription($metadescription)
    {
        $this->metadescription = $metadescription;

        return $this;
    }

    /**
     * Get metadescription
     *
     * @return string
     */
    public function getMetadescription()
    {
        return str_replace(array("\n","\r"), ' ', $this->metadescription);
    }

    /**
     * Set metakeywords
     *
     * @param string $metakeywords
     * @return News
     */
    public function setMetakeywords($metakeywords)
    {
        $this->metakeywords = $metakeywords;

        return $this;
    }

    /**
     * Get metakeywords
     *
     * @return string
     */
    public function getMetakeywords()
    {
        return str_replace(array("\n","\r"), ' ', $this->metakeywords);
    }

    /**
     * Set name
     *
     * @param string $name
     * @return News
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set public_at
     *
     * @param \DateTime $publicAt
     * @return News
     */
    public function setPublicAt($publicAt)
    {
        $this->public_at = $publicAt;

        return $this;
    }

    /**
     * Get public_at
     *
     * @return \DateTime
     */
    public function getPublicAt()
    {
        return empty($this->public_at) ? new \DateTime() : $this->public_at;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return News
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }
}

src/Plugins/NewsBundle/Controller/NewsController.php
<?php

namespace Plugins\NewsBundle\Controller;

use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\DependencyInjection\ContainerInterface;

use AppBundle\Controller\BaseController;
use Plugins\ContentBundle\Entity\Content;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Plugins\NewsBundle\Entity\News;
use Plugins\NewsBundle\Repository\NewsRepository;
// use Symfony\Bundle\FrameworkBundle\Controller\Controller;


class NewsController extends BaseController
{
    const NUMBER_LAST_NEWS_ON_HOMEPAGE = 3;
    const LIMIT_SHOW_NEWS = 10;
    const LIMIT_SHOW_MOZAIC_NEWS = 10;
    const LIMIT_MOZAIC_ITEMS = 1;

    /**
     * News action
     *
     * @param integer $page
     */
    public function newsAction($page = 1, $home = false) {
        $offset = 0;
        if ($page > 1) {
            $offset = self::LIMIT_SHOW_NEWS * ($page - 1);
        }

        $elements = $this->getNewsRepository()->findNews(self::LIMIT_SHOW_NEWS, 'public_at', $offset);
        $pages = ceil(($this->getNewsRepository()->countNews()/self::LIMIT_SHOW_NEWS));
        $news = $this->getNewsRepository()->findLast(self::LIMIT_SHOW_NEWS);

        return $this->render('PluginsNewsBundle:News:news.html.twig', array(
                'content'    => $this->getContentRepository()->findOneByKey(Content::CONTENT_META_NEWS_PAGE),
                'news'       => $news,
                'elements'   => $elements,
                'page'       => $page,
                'pages'      => $pages,
                'queries'    => null,
								'home'			 => $home
            ));
    }

    /**
     * View action
     * @param string $url
     */
    public function viewAction($url) {
				$elements = $this->getNewsRepository()->findNews(self::LIMIT_SHOW_NEWS, 'public_at', 0);
        $page = $active = $this->getNewsRepository()->findOneByUrl($url);
        $news = $this->getNewsRepository()->findLast(self::LIMIT_SHOW_NEWS);

        if (empty($page)) {
            throw new NotFoundHttpException();
        }

        return $this->render('PluginsNewsBundle:News:view.html.twig', array(
                'page'   => $page,
                'elements'   => $elements,
                'news'   => $news,
                'active' => $active
        ));
    }

    /**
     * Render short news list for mozaic block
     */
    public function lastShortListAction() {
        $news = $this->getNewsRepository()->findLast(self::NUMBER_LAST_NEWS_ON_HOMEPAGE);

        return $this->render('PluginsNewsBundle:News:last_short_list.html.twig', array(
                'news'   => $news
            ));
    }

    /**
     * Render short news list
     */
    public function lastMozaicListAction() {
      $news = $this->getNewsRepository()->findLast(self::LIMIT_SHOW_MOZAIC_NEWS);

      return $this->render('PluginsNewsBundle:News:news_mozaic.html.twig', array(
              'news'   => $news
          ));
    }

    /**
     * Render mozaic items
     */
    public function newsMozaicItemsAction() {
      $news = $this->getNewsRepository()->findLast(self::LIMIT_MOZAIC_ITEMS);

      return $this->render('PluginsNewsBundle:News:main-mozaic-news-item.html.twig', array(
              'news'   => $news
          ));
    }


  // O U T _ P U T _ Y O U R _ D A T A
  // echo "<pre>";
  // print_r( \Doctrine\Common\Util\Debug::export($data,1) ); die("oopsy");


    public function newsPostAction() {
      $request = $this->getRequest();
      $requestString = $request->get('searchText');

      $entities = $this->getNewsRepository()->findByString($requestString);
      $en_filtr =  \Doctrine\Common\Util\Debug::export($entities,2);

      return new Response(json_encode($en_filtr));
      // return new Response($em);
    }

}

src/Plugins/NewsBundle/Resources/views/News/last_short_list.html.twig
{% block latestNews %}
    {% if not news is empty%}
    <section class="latest-news">
        <div class="content-row">
            <div class="latest-container">
                <h2 class="title">
                    <img src="{{ asset("images/latest-news-title.png") }}" alt="latest news"/>
                </h2>
                {% for entity in news %}
                    <div class="element {{ loop.first ? "priority" }}">
                        <a href="{{ path('plugins_news_view', {'url' : entity.url}) }}">
                            <h3 class="title">
                                {{ entity.name }}
                            </h3>
                        </a>
                        {{ entity.short | raw }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}
{% endblock %}

src/Plugins/NewsBundle/Resources/views/News/main-mozaic-news-item.html.twig
{% for item in news %}
	{% set x = 0 %}
	{% set break = false %}
	{% set name %}{% endset %}
	{% set text = item.name | split(' ') %}

	<span>
		<a href="{{ path('plugins_news_view', {'url' : item.url}) }}">

			{% for t in text if not break %}
				{% set x = (x + t|length) %}
				{% if (x) < 38 %}
					{{t}}
				{% else %}
				...
					{% set break = true %}
				{% endif %}
			{% endfor %}

		</a>
	</span>


	<p><a href="{{ path('plugins_news_view', {'url' : item.url}) }}" title="news & views">news & views</a></p>

{% endfor %}

src/Plugins/NewsBundle/Resources/views/News/news.html.twig
{% extends 'AppBundle::layout.html.twig' %}

{% block title %}{{- content.metatitle ? content.metatitle : parent() -}}{% include "PluginsNewsBundle:News:page_to_meta_news.html.twig" with {'pages': pages, 'page': page} %}{% endblock %}
{% block meta_keywords %}{{- content.metakeywords ? content.metakeywords : parent() -}}{% endblock %}
{% block meta_description %}{{- content.metadescription ? content.metadescription : parent() -}}{% include "PluginsBlogBundle:Blog:page_to_meta.html.twig" with {'pages': pages, 'page': page} %}{% endblock %}
{% block og_title %}{{- content.metatitle ? content.metatitle : parent() -}}{% include "PluginsBlogBundle:Blog:page_to_meta.html.twig" with {'pages': pages, 'page': page} %}{% endblock %}
{% block og_descr %}{{- content.metadescription ? content.metadescription : parent() -}}{% endblock %}
{% block last_updated_block %}{{ content.updatedAtDatetime}}{% endblock %}

{% block canonicalLinkBlock %}
{# include "default/canonical.html.twig" #}
{% endblock %}

{% block bodyId %}news{% endblock %}
{% block bodyClass %}news{% endblock %}

{% block content %}
<wrapper>

		{#
			{% include "PluginsNewsBundle:News:news_mozaic.html.twig" with { 'elements' : elements}%}
		#}

		{% render controller("PluginsNewsBundle:News:lastMozaicList") %}

		<section id="blog" class="parent container-fluid">
				<div class="row">
						<div class="submenu">

							<div id="side_menu">

								<h2>News & Views</h2>
								<div class="psearch">
										<input type="text" id='search'>
										<!-- <i class="fa fa-search" aria-hidden="true"></i> -->
										<img class="s_pbtn" src="/img/s-icon.svg" alt="">
								</div>

								{# {% include "PluginsBlogBundle:Blog:search_form.html.twig" with { 'queries': queries } %} #}
								<!-- QUERRIES!!! -->

								{# {% render controller("PluginsBlogBundle:Blog:blogVerticalMenu", {categoryId: null, topicId: null, home : false, name : 'News & Vews' }) %} #}

							</div>
							<div class="fb-square">{% include 'default/fb-square.html.twig' %}</div>
						</div>


						{% include "PluginsNewsBundle:News:show_news.html.twig" with { 'home' : true, 'elements' : elements}%}
{#
						<div class="content">
							{% include "default/breadcrumbs.html.twig" with { 'currentPage': 'News & Views', 'elements': {
											0: {'url': "plugins_news_homepage", 'name': "News & Views" }
									}, 'home' : true } %}
							<div class="list">
								<ul>
									{% for entity in elements %}
									<li class="item">
										<a href="{{ path('plugins_news_view', {'url' : entity.url}) }}" title="{{ entity.name }}"><h3>{{ entity.name }}</h3></a>
										<div class="short">
											{{ entity.short | raw }}
										</div>
										<hr>
										<div class="info">
											<div class="row">
												<div class="dc">
													<div class="pattr"><span>date:</span>{{ entity.dateUsFormat }}</div>
												</div>
												<div class="readmore"><a href="{{ path('plugins_news_view', {'url' : entity.url}) }}"><span class="pbtn">read more</span></a></div>
											</div>
										</div>
									</li>
									{% endfor %}
								</ul>
								</div>
						</div>
#}

						<div class="contactus">
								{% include "AppBundle:Contact:contact_block_form.html.twig" %}
								<div class="fb-square">{% include 'default/fb-square.html.twig' %}</div>
						</div>
				</div>
		</section>
</wrapper>
{% endblock %}

src/Plugins/NewsBundle/Resources/views/News/news_menu_list.html.twig
{% block newsMenuList %}
<div class="inner">
    <span class="title">
        news
    </span>
    <div class="news-previews">
        {% for entity in news %}
        <div class="news-preview">
            <a href="{{ entity.id == activeId ? '#' : path('plugins_news_view', {'url' : entity.url}) }}" title="{{ entity.name }}" class="title {{ entity.id == activeId ? "active" }}">
                {{ entity.name }}
            </a>
            <span class="date">{{ entity.dateUsFormat }}</span>
            <p>
                {{ entity.shortSimpleText }}
            </p>
            <a href="{{ entity.id == activeId ? '#' : path('plugins_news_view', {'url' : entity.url}) }}" class="readmore">read more</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

src/Plugins/NewsBundle/Resources/views/News/news_mozaic.html.twig
<section id='p_table'>

	<div class="part f">

	{% set item %}{% endset %}
	{% set break = false %}
	{% set type = {
		1: 'f',
		2: 's',
		3: 't',
		4: 'f',
		5: 's',
		6: 't',
		7: 'fth',
		8: 'f',
		9: 's',
		10: 't'
	} %}
	{% set mask = {
		1: 'a',
		2: 'b',
		3: 'b',
		4: 'c',
		5: 'a',
		6: 'a',
		7: 'c',
		8: 'b',
		9: 'a',
		10: 'b'
	} %}


	<!-- LOOP -->

	{% for entity in news if not break %}

	{% if loop.index is odd %}
    <div class="block back {{type[loop.index]}}">
	{% else %}
    <div class="block {{type[loop.index]}}">
	{% endif %}


			<div class="mask {{mask[loop.index]}}"></div>
			<div class="wrapper">
				<div class="cover">
					<a href="{{ path('plugins_news_view', {'url' : entity.url}) }}" title="{{ entity.name }}">
						<h3>{{ entity.name }}</h3>
						{% if mask[loop.index] == 'a' %}
						<span class="link">
						{% else %}
						<span class="link_gray">
						{% endif %}
							read more
						</span>
					</a>
				</div>
			</div>
		</div>

	{% if loop.index == 3 %}
	</div>

	<div class="part s">
	{% endif %}
	{% if loop.index == 7 %}
	</div>

	<div class="part t">
	{% endif %}
	{% if loop.index == 10 %}
		{% set break = true %}
	{% endif %}
	{% endfor %}

	<!-- END LOOP -->

	</div>

</section>

src/Plugins/NewsBundle/Resources/views/News/page_to_meta_news.html.twig
{% block pageToMetaNews %}
	{% spaceless %}
	{% if (page == 1) %} - Law office of Yelena Sharova{% endif %}
	{% if (pages > 1) %}
	{% if (page != 1) %}
	&nbsp;- Page {{ page }}
	{% endif %}
	{% endif %}
	{% endspaceless %}
{% endblock %}

src/Plugins/NewsBundle/Resources/views/News/page_to_name_news.html.twig
{% block pageToName %}
    {% spaceless %}
    {% if (pages > 1) %}
      {% if (page != 1) %}
        &nbsp;- Page {{ page }}
      {% endif %}
    {% endif %}
	{% endspaceless %}
{% endblock %}

src/Plugins/NewsBundle/Resources/views/News/show_news.html.twig
<style>
    #news-filtered{
      display: none;
    }
</style>

<div class="content">
<!-- _________________ -->
  {% if home == true %}
<!-- _________________ -->
    {% include "default/breadcrumbs.html.twig" with { 'currentPage': 'News & Views', 'elements': {
            0: {'url': "plugins_news_homepage", 'name': "News & Views" }
        }, 'home' : true } %}
    <div class="list" id="news-show">
      <ul id='statis_show'>
        {% for entity in elements %}
        <li class="item">
          <a href="{{ path('plugins_news_view', {'url' : entity.url}) }}" title="{{ entity.name }}"><h3>{{ entity.name }}</h3></a>
          <div class="short">
            {{ entity.short | raw }}
          </div>
          <hr>
          <div class="info">
            <div class="row">
              <div class="dc">
                <div class="pattr"><span>date:</span>{{ entity.dateUsFormat }}</div>
              </div>
              <div class="readmore"><a href="{{ path('plugins_news_view', {'url' : entity.url}) }}"><span class="pbtn">read more</span></a></div>
            </div>
          </div>
        </li>
      {% endfor %}
      </ul>
    </div>
<!-- _________________ -->
  {% else %}
<!-- _________________ -->
	  {% include "default/breadcrumbs.html.twig" with { 'currentPage': element.name, 'elements': { 0: {'url': "plugins_news_homepage", 'name': "News & Views" }}, 'home' : false } %}
    <div class="txt" id="news-show">
      {% if element %}
      <h1>{{ element.name }}</h1>
      <div class="postdate">{{ element.dateUsFormat }}</div>
      {{ element.content | raw }}
      {% endif %}
      <hr>
      {% include "default/fb.html.twig" %}
    </div>
<!-- _________________ -->
  {% endif %}
<!-- _________________ -->
  <div class="list" id="news-filtered">
    <ul id='search_show'>
    </ul>
  </div>
<!-- _________________ -->
</div>

<script type="text/javascript">
    jQuery(document).ready(function() {
      var searchRequest = null;
      $("#search").val('');

      console.log('search');

      $("#search").on('keyup',function() {

          var that = this;
          var value = $(this).val();

          var entitySelector = $("#search_show").html('');
          if ( $(this).val().length > 0 ) {
              if (searchRequest != null)
                  searchRequest.abort();
              $('#search_show').empty()

              $.ajax({
                  type: "POST",
                  url: "{{ path('news_ajax_search') }}",
                  data: {
                      'searchText' : value
                  },
                  success: function(msg){
                    console.log('responce');
                    //we need to check if the value is the same
                    if (value==$(that).val()) {
                        var result = JSON.parse(msg);
                        console.log(result);

                        $('#news-show').slideUp("fast");
                        var content = '';
                        if(result.length == 0){
                          content += '<li>no result...</li>';
                        }else{
                          for(var i=0; i < result.length; i++){
                            content +=
                            '<li class="item">'+
                              '<a href="/news/'+
                              result[i]['url']+
                              '"title="'+result[i]['name']+'">'+
                              '<h3>'+result[i]['name']+'</h3>'+
                              '</a>'+
                              // '<div class="short">'+
                              //   result[i]['short']+
                              // '</div>'+
                              '<hr>'+
                              // '<div class="info">'+
                              //   '<div class="row">'+
                                  // '<div class="dc">'+
                                  //   '<div class="pattr">'+
                                  //   '<span>date:</span>'+
                                  //   'time....'+
                                  //   '</div>'+
                                  // '</div>'+
                              //     '<div class="readmore">'+
                              //     '<a href="news/'+
                              //     result[i]['url']+
                              //     '"><span class="pbtn">'+
                              //     'read more'+
                              //     '</span>'+
                              //     '</a>'+
                              //     '</div>'+
                              //   '</div>'+
                              // '</div>'+
                            '</li>';
                          }
                        }
                        $('#search_show').append(content);
                        $('#news-filtered').slideDown('fast');
                      }
                   }
              });
          }// if( $(this).val().length > 0 )
          else{
            $('#news-filtered').slideUp('fast');
            $('#news-show').slideDown('fast');
          }

        });// #search on 'keyup'
    });
</script>

src/Plugins/NewsBundle/Resources/views/News/view.html.twig
{% extends 'AppBundle::layout.html.twig' %}

{% block title %}{{- page.metatitle ? page.metatitle : parent() -}}{% endblock %}
{% block meta_keywords %}{{- page.metakeywords ? page.metakeywords : parent() -}}{% endblock %}
{% block meta_description %}{{- page.metadescription ? page.metadescription : parent() -}}{% endblock %}
{% block og_title %}{{- page.metatitle ? page.metatitle : parent() -}}{% endblock %}
{% block og_descr %}{{- page.metadescription ? page.metadescription : parent() -}}{% endblock %}
{% block last_updated_block %}{{ page.updatedAtDatetime}}{% endblock %}

{% block bodyId %}blog{% endblock %}

{% block content %}
<wrapper>
		{% render controller("PluginsNewsBundle:News:lastMozaicList") %}
		<section id="blog" class="parent container-fluid">
				<div class="row">
					<div class="submenu">

							<div id="side_menu">

								<h2>News & Views</h2>
								<div class="psearch">
										<input type="text" id='search'>
										<!-- <i class="fa fa-search" aria-hidden="true"></i> -->
										<img class="s_pbtn" src="/img/s-icon.svg" alt="">
								</div>
								{# {% include "PluginsBlogBundle:Blog:search_form.html.twig" with { 'queries': queries } %} #}
								<!-- QUERRIES!!! -->

							{# {% render controller("PluginsBlogBundle:Blog:blogVerticalMenu", {categoryId: null, topicId: null, home : false, name : 'News & Vews' }) %} #}

							<!-- {% include "PluginsPracticAreaBundle:PracticArea:google_map_pa.html.twig" %} -->
						</div>
						<div class="fb-square">{% include 'default/fb-square.html.twig' %}</div>
				</div>


				{% include "PluginsNewsBundle:News:show_news.html.twig" with { 'home' : false, 'element' : active}%}

				{#
				<div class="content">
					{% include "default/breadcrumbs.html.twig" with { 'currentPage': active.name, 'elements': { 0: {'url': "plugins_news_homepage", 'name': "News & Views" }}, 'home' : false } %}


					<div class="txt">
						{% if active %}
						<h1>{{ active.name }}</h1>
						<div class="postdate">{{ active.dateUsFormat }}</div>
						{{ active.content | raw }}
						{% endif %}

						<hr>
						{% include "default/fb.html.twig" %}
					</div>
				</div>
				#}

				<div class="contactus">
						{% include "AppBundle:Contact:contact_block_form.html.twig" %}
						<div class="fb-square">{% include 'default/fb-square.html.twig' %}</div>
				</div>
					</div>
			</section>
	</wrapper>
{% endblock %}